### ISSUE TITLE
Refactor usage of storeManager in the plugin

### ISSUE THREAD

**Issue by olsi-qose** [Nosto/nosto-magento2-cmp#101]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Use a helper method to get the store instead of calling `storeManager->getStore` in different places.

**Describe alternatives you've considered**

**Additional context**

**Comment by mridang** [comment]
We should not create any more helpers. The one that we should use should come from the core plugin. https://github.com/Nosto/nosto-magento2/blob/develop/Helper/Scope.php
